### ISSUE TITLE
Поправьте url, у вас в консольке 404 ошибки

### ISSUE THREAD

**Issue by coursar** [Ruslan04071996/EigthHomework#4]
![Screenshot from 2019-12-15 17-33-20](https://user-images.githubusercontent.com/3601892/70864212-05ee1800-1f61-11ea-9ecb-459dcc70a823.png)
https://github.com/Ruslan04071996/EigthHomework/blob/41fdb8fcd946443914fec87b70d7b6c3d93cc2b4/app.js#L3

**Comment by Ruslan04071996** [comment]
исправил

**Comment by Ruslan04071996** [comment]
исправил
